name: esoui-downloads

services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./src/core:/app/core:ro
      - ./src/app:/app/app:ro
    env_file:
      - .env
    restart: unless-stopped

  flow:
    build:
      context: .
      dockerfile: ./data-pipeline.Dockerfile
    restart: unless-stopped
    volumes:
      - ./output:/app/output
    env_file:
      - .env


volumes:
  data:
