[project]
name = "data-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fake-useragent>=2.2.0",
    "pandas>=2.3.2",
    "prefect>=3.4.14",
    "requests>=2.32.5",
]
